<?php

namespace News\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
    public function findByCategory($id){
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->add("where","a.categoryId = $id")
            ->getQuery()
            ->getResult();
        return $qb;
    }
}
