<?php

namespace News\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use News\MainBundle\Entity\Articles;
use Padam87\SearchBundle\Filter\Filter;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
    public function findByCategory($id){
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->add("where","a.categoryId = $id")
            ->getQuery()
            ->getResult();
        return $qb;
    }

//    public function getArticles($qb){
//        $qb = $qb->getQuery()
//            ->getResult();
//        return $qb;
//    }

    public  function search($word, $order = 'ASC')
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.title LIKE :word')
            ->orWhere('a.articles LIKE :word')
            ->orWhere('a.short_text LIKE :word')
            ->setParameter('word', '%'.$word.'%')
            ->orderBy('a.id',$order)
            ->getQuery()
            ->getResult();
        return $qb;

    }
}
