<?php

namespace News\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * OnLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlineRepository extends EntityRepository
{
    public function getUsersOnline(){
        $date = new \DateTime('-3 minute');
        $qb = $this->createQueryBuilder('o')
            ->where("o.lastVisit > :date")
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult();
        return $qb;
    }

    public function deleteUsersOfflineFromDb(){
        $date = new \DateTime('-3 minute');
        $qb = $this->createQueryBuilder('o')
            ->delete()
            ->where("o.lastVisit < :date")
            ->setParameter('date', $date)
            ->getQuery()
            ->execute();
        return $qb;
    }
}
